name: Update ROCK

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@main
    with:
      rock-name: prometheus-pushgateway
      source-repo: prometheus/pushgateway
      check-go: true
      update-script: |
        # The caller must provide \$application_src and \$rockcraft_yaml
        #   \$application_src: The root folder of the cloned upstream project
        #   \$rockcraft_yaml: Path of the rockcraft.yaml to update
        #
        ## Node dependency
